server_port:  5001
auto: true
sitename: Sierra Project
repo: "https://github.com/seyyedshah/sierra"
wiki: "https://github.com/seyyedshah/sierra/wiki"
tracker: "https://github.com/seyyedshah/sierra/issues"